[tool.poetry]
name = "fast-llm"
version = "0.1.0"
description = ""
authors = ["Vidith Balasa"]

[tool.poetry.dependencies]
python = "^3.10"
vllm = "^0.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
